# Generated by Django 5.1.7 on 2025-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
