# Generated by Django 5.1.7 on 2025-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('specialist', 'Specialist'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
