# Generated by Django 5.1.7 on 2025-04-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_comment_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
    ]
