# Generated by Django 5.1.7 on 2025-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='instruction',
            new_name='description_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
