# Generated by Django 5.1.7 on 2025-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Название тега на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Название тега на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(default=1, max_length=100, verbose_name='Название тега на узбекском'),
            preserve_default=False,
        ),
    ]
