# Generated by Django 5.1.7 on 2025-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_tag_name_tag_name_en_tag_name_ru_tag_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=100),
        ),
    ]
