# Generated by Django 5.1.7 on 2025-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_age_alter_tag_name_en_alter_tag_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='age_range',
            field=models.CharField(choices=[('0-2', '0-2 years (Infants)'), ('3-7', '3-7 years (Young Children)'), ('8-12', '8-12 years (Children)'), ('13-17', '13-17 years (Teenagers)'), ('18+', '18+ years (Adults)')], default='18+', max_length=10),
        ),
    ]
