# Generated by Django 5.1.7 on 2025-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_age_product_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
