# Generated by Django 5.1.7 on 2025-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='answer_ru',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
