# Generated by Django 5.1.7 on 2025-04-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_answer_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='links',
        ),
    ]
